Refactor of animation zone
Adityamaurya123uma/Algorith_Visualizer pull request #14
Opened 2023-10-12 16:48 UTC by Adityamaurya123uma

Refactor of animation zone

2023-10-12 16:49 UTC, Adityamaurya123uma commented
@Deependra3010 Can you please have a look at this PR. I had refactored the animation zone with better animation.

2023-10-12 17:36 UTC, Adityamaurya123uma commented
@Deependra3010 Can you recheck now. I just added another commit.

2023-10-12 17:41 UTC, Deependra3010 commented
> @Deependra3010 Can you recheck now. I just added another commit.

Better Now could you have a look at speed, at minimum speed 1 also its too fast it does not event take 1sec to sort.

2023-10-12 17:47 UTC, Adityamaurya123uma commented
@Deependra3010 Yes, the speed, actually it work reverse at the moment, meaning 1  indicates fast and 10 indicates slow.
I'll handle it.

2023-10-12 18:20 UTC, Deependra3010 commented
@Adityamaurya123uma Just a few issue's and some suggestion otherwise look's good!!!

2023-10-13 12:13 UTC, Deependra3010 requested changes

2023-10-24 16:29 UTC, Adityamaurya123uma commented on algorithm-visualizer/src/components/content/animationzone.js
> +        />
I can do this in future commits once the animation zone is fully built. I added todo for now, that would remind me later

2023-10-24 16:37 UTC, Adityamaurya123uma commented
@Deependra3010 All the changes suggested by you are done.

2023-10-24 23:57 UTC, Deependra3010 approved these changes

2023-10-24 23:58 UTC, merged